### ISSUE TITLE
Migrate to apache camel

### ISSUE THREAD

**Issue by matthewwilson** [yokall/video_recording_handler#7]
This could be solved with a 1 liner using camel. Good day sir

**Comment by yokall** [comment]
While I don't dispute that the purpose of this project is 2 fold

1. I wanted something to manage the storing of video files
2. I want a simple enough project using Perl the language I use at work to experiment with test frameworks, CI/CD and other development techniques

While 1 could be solved with Camel 2 requires Perl :P
